version: "3.8"

services:
    client:
        build: ./client
        container_name: client
        ports:
            - "5030:80"
        restart: always

    server:
        build: ./server
        container_name: server
        ports:
            - "5031:8080"
        restart: always
